# Base configuration
permalink: /news/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
pygments: true

#Prose.io editing info
repo_name: open-source-program
branch: gh-pages
#GitHub organization name *or* username
gh_org: 18f
prose_url: http://github.com/
site_url: http://18f.github.io/open-source-program
media: assets/img


# Your Programs's Name
name: Government Open Source
subtitle: Material to support open source in government 

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/open-source-program'

# Author/Organization info to be displayed in the templates
author:
  name: 18F 
  url: http://localhost:4000

# ------------------------------------------------------------------
#   Navigation
#   List links that should appear in the site sidebar here
#   "pages" is a directory to keep web content that are not posts
# ------------------------------------------------------------------
navigation:
- text: Home
  url: index.html
  internal: true
- text: Policy Documents
  url: pages/policy_documents.html
  internal: true 
- text: FAQs
  url: pages/faq.html
  internal: true 
- text: Other Pages
  url: pages/other_pages.html
  internal: true 
- text: Feedback
  url: https://github.com/18F/open-source-program/issues
  internal: true 



